disabled_rules:
  - trailing_whitespace
  - line_length
  - variable_name
  - file_length
  - function_body_length
  - opening_brace
  - type_body_length
  - valid_docs
  - function_parameter_count
  - type_name
  - force_try
  - conditional_binding_cascade
